name: social_media_manager
description: "A premium social media account manager."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  sqflite: ^2.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.2
  local_auth: ^2.1.8
  encrypt: ^5.0.3
  csv: ^5.0.2
  font_awesome_flutter: ^10.7.0
  fl_chart: ^0.65.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
